name: CI Build

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/build.yml'
      - '**/*.js'
      - 'package.json'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/build.yml'
      - '**/*.js'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: checkout
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run all
